system:
  title: 'ストレングスファインダー管理サービス'
  url: 'http://localhost:3000/'
  bbs_url: 
  trello_url: 
  google_form_url: 
  official_twitter_id: 'newburu'
  description: 'ストレングスファインダーを管理するサービスです！'
  description_smartphone: 'ストレングスファインダー管理サービス！'
  hashtag: 'ストレングスファインダー管理サービス'
  keywords: ['ストレングスファインダー管理']
  twitter_site: newburu
  twitter:
    url: 'https://twitter.com/'
    tweet_url: 'http://twitter.com/intent/tweet'
    share_url: 'http://twitter.com/share'
  facebook:
    share_url: 'https://www.facebook.com/share.php'
  line:
    share_url: 'https://social-plugins.line.me/lineit/share'
  mail:
    share_url: 'mailto:'
  default:
    user_name: 名無し
